### ISSUE TITLE
Extending the parser

### ISSUE THREAD

**Issue by 6r1d** [BinaryNate/midi-message-parser#2]
Hello. I have tinkered with "midi-message-parser" a bit and I decided to change some things. These changes might be useful in the main project (or not really).

For starters, there's a `C` file and a header. I decided that splitting everything into several header files might be better than including a C file in all projects using the library or building a `.so` file. It would be nice to know if it is a breaking change.

What interests me especially is extending the parsing functionality. I created a "[bytereader](https://github.com/6r1d/midi-message-parser/tree/bytereader)" branch in my fork for that.
Now it can select note frequencies and velocities from a `struct`, handle some MIDI CC messages and ignores stuff like pitch bend range update for now. (Frequency values for MIDI keys are precalculated and included in constants.)
Are there other commands useful for extending it besides `note_on`, `note_off` and `cc`?

I see Doxygen-style comments, too. Would adding a Sphinx for documentation generation be alright? I'm thinking about it, because it'll allow pages not related to code documentation directly, like "Examples". (I don't know Doxygen that well.)

**Comment by binarynate** [comment]
Hi, Victor 👋. Thanks for the details and for your offer to contribute changes! It's been several years since I wrote and used this MIDI library, and I don't have any plans to continue using it in the near future, but I like keeping it on GitHub in case I have a use for it in the future. Since you're actively improving and augmenting the code (which I think is great), my suggestion is to go full speed ahead in your fork and leave this repo as-is for now. That way, I won't be holding back your progress, and people can find your fork through this repo's fork link. Thanks for your offer to contribute changes back, though!

**Comment by 6r1d** [comment]
> my suggestion is to go full speed ahead in your fork and leave this repo as-is for now

Sure thing, thanks!

> Thanks for your offer to contribute changes back, though!

I was really concerned about breaking compatibility with some existing project, so I wasn't changing some parts much.
It's good to know I can change it without breaking stuff.
